
[functions.telegram-bot]
enabled = true
verify_jwt = false
import_map = "./functions/telegram-bot/deno.json"
entrypoint = "./functions/telegram-bot/index.ts"

[functions.whatsapp-bot]
enabled = true
verify_jwt = false
import_map = "./functions/whatsapp-bot/deno.json"
entrypoint = "./functions/whatsapp-bot/index.ts"
