export const callesResistencia = [
  "1 de Enero",
  "12 de Octubre",
  "17 de Agosto",
  "20 de Junio",
  "8 de Diciembre",
  "ARA San Juan",
  "Aarón de Anchorena",
  "Acceso Barrio Los Tucanes",
  "Acceso Norte a Ruta Nacional 11",
  "Acceso Sur a Ruta Nacional 11",
  "Acceso a Aeropuerto de Resistencia",
  "Acceso a Barrio La Ribera",
  "Acceso a Motel",
  "Adelina Del Carril",
  "Adolfo Pérez Esquivel",
  "Agrimensor Agustín Foster",
  "Aguará Guazú",
  "Agustín Andreani",
  "Alabanza",
  "Alberto Castillo",
  "Alberto Gerardo Ivancovich",
  "Alberto Torres",
  "Aldo Boglietti",
  "Alemania",
  "Alfonsina Storni",
  "Alfredo Pértile",
  "Alfredo Veiravé",
  "Alice Le Saige",
  "Alicia Moreau de Justo",
  "Aliso",
  "Almirante Brown",
  "Amabilidad",
  "Ameghino",
  "Amor",
  "América",
  "Antequeras",
  "Antonio Arancibia",
  "Antonio Berutti",
  "Antonio Brignole",
  "Antonio De Marchi",
  "Aníbal Troilo",
  "Arazá",
  "Arbo y Blanco",
  "Argentina",
  "Aristóbulo de Valle",
  "Armando Anello",
  "Arminda Rogiolo",
  "Arquitecto Bruno del Mónico",
  "Artur Luissone",
  "Arturo Frondizi",
  "Arturo Lestani",
  "Arturo Umberto Illia",
  "Asamblea",
  "Asunción",
  "Atilio López",
  "Australia",
  "Autovía Nicolás Avellaneda",
  "Avendida Arboledas",
  "Avenida 25 de Mayo",
  "Avenida 9 de Julio",
  "Avenida Agrimensor Seelstrang",
  "Avenida Alberdi",
  "Avenida Alfredo Guerrero",
  "Avenida Antonio Martina",
  "Avenida Arribálzaga",
  "Avenida Arturo Jauretche",
  "Avenida Belgrano",
  "Avenida Bogotá",
  "Avenida Brigadier General Juan Manuel de Rosas",
  "Avenida Carlos López Piacentini",
  "Avenida Carlos María de Alvear",
  "Avenida Carmen C. Viuda de Ross",
  "Avenida Carmen Vilallave de Ross",
  "Avenida Centro",
  "Avenida Chaco",
  "Avenida Coronel Falcón",
  "Avenida Doctor Antonio Álvarez Lottero",
  "Avenida España",
  "Avenida Felipe Gallardo",
  "Avenida Hernandarias",
  "Avenida Hortensio Quijano",
  "Avenida Intendente Borrini",
  "Avenida Islas Malvinas",
  "Avenida Italia",
  "Avenida Juan José Castelli",
  "Avenida Juana Azurduy",
  "Avenida Laprida",
  "Avenida Las Heras",
  "Avenida Lavalle",
  "Avenida Lonardi",
  "Avenida Luis Ángel Firpo",
  "Avenida Mac Lean",
  "Avenida Marconi",
  "Avenida Moreno",
  "Avenida Nicaragua",
  "Avenida Nicolás Rojas Acosta",
  "Avenida Padre Rissione",
  "Avenida Paraguay",
  "Avenida Rivadavia",
  "Avenida Rodríguez Peña",
  "Avenida Sabín",
  "Avenida San Martín",
  "Avenida Sarmiento",
  "Avenida Soberanía Nacional",
  "Avenida Urquiza",
  "Avenida Vélez Sarsfield",
  "Avenida Wilde",
  "Avenida de la Democracia",
  "Avenida de la Gratitud",
  "Avenida de los Inmigrantes",
  "Avenida del Bicentenario",
  "Avenida Ávalos",
  "Avenida Édison",
  "Avia Terai",
  "Ayacucho",
  "Ayrton Senna",
  "Bailecito",
  "Baltazar Tatalo Domínguez",
  "Bartolina Sissa",
  "Bartolomé Mitre",
  "Baruc",
  "Basail",
  "Belén",
  "Bendición",
  "Benignidad",
  "Benito Juárez",
  "Benjamín Zorrilla",
  "Bermejo",
  "Bernardo Alberto Houssay",
  "Bibiano Meza",
  "Bicisenda",
  "Blas Parera",
  "Bolivia",
  "Bondad",
  "Boris Afanasenko",
  "Brasil",
  "Brasilia",
  "Brigadier Parodi",
  "Bélgica",
  "Cabildo",
  "Cacique Luis García",
  "Cacique Pelayo",
  "Cacique Vahenolec",
  "Cacique Ñaré",
  "Calandria",
  "Calle 1",
  "Calle 10",
  "Calle 14",
  "Calle 2",
  "Calle 26",
  "Calle 27",
  "Calle 28",
  "Calle 29",
  "Calle 3",
  "Calle 30",
  "Calle 31",
  "Calle 32",
  "Calle 4",
  "Calle 6",
  "Calle 7",
  "Calle 8",
  "Calle 9",
  "Campo Largo",
  "Canadá",
  "Cangallo",
  "Capataz Codutti",
  "Capitán Pedro Giachino",
  "Capitán Solari",
  "Carabobo",
  "Caracas",
  "Carau",
  "Cardenal",
  "Carlos Boggio",
  "Carlos Campia",
  "Carlos Corsi",
  "Carlos Dodero",
  "Carlos Gardel",
  "Carlos Hardy",
  "Carlos Lutringer",
  "Carlos Saavedra Lamas",
  "Carlos Tejedor",
  "Carnavalito",
  "Cartero Bruno Ramírez",
  "Catamarca",
  "Cataratas del Iguazú",
  "Cecilia Perdora de Serens",
  "Celedonio Flores",
  "Celmira Gonzevat de Cabral",
  "Cervantes",
  "Chacabuco",
  "Chacarera",
  "Chamamé",
  "Chamarrita",
  "Chapadmalal",
  "Charadai",
  "Charata",
  "Chile",
  "Chorote",
  "Chubut",
  "Chulupí",
  "Ciclón",
  "Cielito",
  "Ciervo Petiso",
  "Ciervo de los Pantanos",
  "Cigüeña",
  "Cipriano Reyes",
  "Ciudad de Cafayate",
  "Ciudad de Charata",
  "Claudio Zapico",
  "Colombia",
  "Colonia Baranda",
  "Colonia Benítez",
  "Colonia Elisa",
  "Colón",
  "Comandante Andresito",
  "Comandante Fontana",
  "Combate de la Vuelta de Obligado",
  "Concepción del Bermejo",
  "Condición",
  "Congreso",
  "Coronel Falcón",
  "Corrientes",
  "Cote Lai",
  "Crisanto Domínguez",
  "Cristófani",
  "Crucero Belgrano",
  "Cuba",
  "Cueca",
  "César Milstein",
  "Córdoba",
  "Dante Emiliozzi",
  "Darío Miró",
  "De Sucre",
  "Deán Funes",
  "Dionicio Suero",
  "Directorio",
  "Doctor Alfredo Parodi",
  "Doctor Alfredo Reggiardo",
  "Doctor Antonio de Grandi",
  "Doctor Diego De Morgan",
  "Doctor Domenech",
  "Doctor Evaristo Ramírez",
  "Doctor Juan Diego De Morgan",
  "Doctor Luis Govi",
  "Doctor Lázaro Maderna",
  "Doctor M. C. Bortagaray",
  "Doctor Mauricio Jajam",
  "Doctor Miguel María Giménez",
  "Doctor Rivero Sosa",
  "Doctora Josefa Palacios",
  "Doctora Maglioli Palacios",
  "Domingo Cubells",
  "Domingo Matheu",
  "Don Bosco",
  "Don Segundo Sombra",
  "Donato Geraldi",
  "Dos de Abril de 1982",
  "Dos de Febrero",
  "Dr. Luis Govi",
  "Dr. Lázaro Moderna",
  "Echeverría",
  "Ecuador",
  "Edmundo Rivero",
  "Eduardo Gerónimo Orcola",
  "Eduardo Newbery",
  "Eduardo Romero",
  "El Pintado",
  "El Salvador",
  "El Sauzalito",
  "Emilio R. Román",
  "Enrique Discépolo",
  "Enrique Kistermacher",
  "Enrique Larreta",
  "Entrada a Ex Estación Ferrocarril Santa Fe",
  "Entre Ríos",
  "Ernesto Duvivier",
  "Escalera de Colores",
  "Escondido",
  "Estanislao López",
  "Estefanía Zelaya de González",
  "Esther Machicote de Díaz",
  "Eugenio Salom",
  "Eva Perón",
  "Ex Combatiente Adolfo Vallejos",
  "Ex Combatiente E. Discépolo",
  "Ezequiel",
  "Facón Grande",
  "Falucho",
  "Favio Cáceres",
  "Fe",
  "Federico Leloir",
  "Feliciano Chiclana",
  "Felipe Molina",
  "Felipe Varela",
  "Fernando L. Martín",
  "Florida",
  "Formosa",
  "Fortín Aguilar",
  "Fortín Alvarado",
  "Fortín Arenales",
  "Fortín Cardozo",
  "Fortín Charrúa",
  "Fortín Chilcas",
  "Fortín Cinco Hermanos",
  "Fortín Expedición",
  "Fortín Lapacho",
  "Fortín Las Chuñas",
  "Fortín Lavalle",
  "Fortín Loma Negra",
  "Fortín Los Pozos",
  "Fortín Piris",
  "Fortín Rivadavia",
  "Fortín Tapenagá",
  "Fortín Timbó",
  "Fortín Warnes",
  "Fortín Wilde",
  "Francia",
  "Francisco Ptak",
  "Francisco Ramírez",
  "Francisco de P. Santander",
  "Franklin",
  "Fray Bertaca",
  "Fray Capelli",
  "Fray Gabriel Grotti",
  "Fray Luis Beltrán",
  "Fray Pérez de Marchena",
  "Fray Rossi",
  "French",
  "Fuerte Esperanza",
  "G. Goubat",
  "Galería Alberdi",
  "Galería Mara",
  "Galería Strugo",
  "Gancedo",
  "García Merou",
  "García Pulido",
  "Gato",
  "Gaucho Rivero",
  "Gaza",
  "General Dónovan",
  "General Fotheringam",
  "General Mansilla",
  "General Obligado",
  "General Pinedo",
  "General Uriburu",
  "General Vedia",
  "George Washington",
  "Gerardo Varela",
  "Germán Abdala",
  "Gertrudis Medeiro",
  "Gertrudis Medeiros",
  "Gervasio Artigas",
  "Gobernador Anselmo Zoilo Ducca",
  "Gobernador Bosch",
  "Gobernador Danilo Baroni",
  "Gobernador Deolindo Felipe Bittel",
  "Gobernador Florencio Tenev",
  "Gobernador Gabriel Carrasco",
  "Gobernador Rolando Tauguinas",
  "Gozo",
  "Guatambú",
  "Guatemala",
  "Guaycurú",
  "Guido Miranda",
  "Guido Spano",
  "Gustavo Lagerheim",
  "Güemes",
  "Gütemberg",
  "Haití",
  "Halcones Criollos",
  "Heraclio Pérez",
  "Hermanos Boronat",
  "Hermanos Palotinos",
  "Hermanos Pinzón",
  "Hilarión de la Quintana",
  "Hipólito Vieytes",
  "Hipólito Yrigoyen",
  "Holanda",
  "Homero Manzi",
  "Honduras",
  "Honestidad",
  "Honorio Ortiz",
  "Horacio Quiroga",
  "Hornero",
  "Huanquero",
  "Huella",
  "Humaitá",
  "Héctor Freschi",
  "Ildefonso Pérez",
  "Independencia",
  "Ingeniero Augusto Schur",
  "Ingeniero Foussal",
  "Ingeniero Luis Fousal",
  "Inmaculada Concepción",
  "Inspector Patiño",
  "Irene B. de Etcheberrigaray",
  "Irene B. de Etcheverrigaray",
  "Irupé",
  "Isabel la Católica",
  "Isaías",
  "Isla Soledad",
  "Isla del Cerrito",
  "Jeremías",
  "Jericó",
  "Jilguero",
  "Joel",
  "Jorge Luis Borges",
  "Jorge Rafael Obligado",
  "José Alsina",
  "José Ameri",
  "José Hernández",
  "José Ignacio Rucci",
  "José Luna",
  "José Martí",
  "José María Paz",
  "José María Toledo",
  "José Mármol",
  "José Navarro",
  "José Noveri",
  "José Rondeau",
  "Juan A. Álvarez Condarco",
  "Juan B. Azopardo",
  "Juan B. Justo",
  "Juan Domingo Perón",
  "Juan Facundo Quiroga",
  "Juan Felipe Ibarra",
  "Juan Godoy",
  "Juan José Paso",
  "Juan Larrea",
  "Juan Manuel Bordeau",
  "Juan Manuel Fangio",
  "Juan Manuel Rossi",
  "Juan Moro",
  "Juan P. Duarte",
  "Juan Polí",
  "Juan Ramón Lestani",
  "Juan XXIII",
  "Juan de Dios Mena",
  "Juan de la Cruz Navarro",
  "Juana Moro",
  "Juanelraic",
  "Jujuy",
  "Julio Argentino Roca",
  "Julio Cortázar",
  "Julio César Perrando",
  "Julio E. Acosta",
  "Julio Guillén",
  "Julio Tort",
  "L. Quintana",
  "La Cangayé",
  "La Eduvigis",
  "La Leonesa",
  "La Palmera",
  "La Pampa",
  "La Paz",
  "La Rioja",
  "La Rábida",
  "La Sabana",
  "La Tigra",
  "Lago Argentino",
  "Lago Nahuel Huapi",
  "Laguna del Desierto",
  "Las Azucenas",
  "Las Margaritas",
  "Las Orquídeas",
  "Las Palmas",
  "Laurel",
  "Lautaro",
  "Lavalle",
  "Lavardén",
  "Leandro N. Alem",
  "Leo Parzianello",
  "Leopoldo Lugones",
  "Leopoldo Martín",
  "León Zorrilla",
  "Leónidas González Montaner",
  "Libertad",
  "Libertador",
  "Lidia Angélica Rapazzioli de Bernal",
  "Lima",
  "Lincoln",
  "Lino Torres",
  "Lisandro de la Torre",
  "Lonardi",
  "Lorenzo Eusebione",
  "Los Andes",
  "Los Aromos",
  "Los Claveles",
  "Los Crisantemos",
  "Los Frentones",
  "Los Gladiolos",
  "Los Hacheros",
  "Los Jazmines",
  "Los Lirios",
  "Los Pinos",
  "Luis De las Casas",
  "Luis Govi",
  "Luis O. Gusberti",
  "Luis Vernet",
  "Luisa Dora Cardozo de Galíndez",
  "Lutringer",
  "López Vicuña",
  "López y Planes",
  "Machagai",
  "Maipú",
  "Makallé",
  "Malambo",
  "Manuel Alberti",
  "Manuel Dorrego",
  "Manuel Lisandro Peralta",
  "Manuel Peralta",
  "Manuel de Sarratea",
  "Mar del Plata",
  "Marcelino Castelán",
  "Marcelo Torcuato de Alvear",
  "Marcos Briolini",
  "Marcos Paz",
  "Margarita Belén",
  "Mario Bandeo",
  "Mario Nestoroff",
  "Mario Villalva",
  "Martina Silva de Gurruchaga",
  "Martín Coronado",
  "Martín Dobrizhoffer",
  "Martín Goitía",
  "Martín Lestani",
  "Martín de Álzaga",
  "María Cuberli",
  "María Moisán",
  "María R. Del Valle",
  "María Remedios del Valle",
  "María Sáenz de Vernet",
  "Mataco",
  "Matará",
  "Mauricio Feldman",
  "Mburucuyá",
  "Mendoza",
  "Micaela Bastida",
  "Miguel Cané",
  "Miguel Z. Delfino",
  "Miguel de Azcuénaga",
  "Minué",
  "Misionero Klein",
  "Misiones",
  "Mocoví",
  "Monseñor Alumni",
  "Monseñor Angelelli",
  "Monseñor De Nevares",
  "Monseñor Romero",
  "Monseñor de Carlo",
  "Monseñor de Nevares",
  "Monteagudo",
  "Montevideo",
  "Morel",
  "México",
  "Napalpí",
  "Napenay",
  "Nataxala' Leoncito",
  "Nazareno Roscian",
  "Nazareno Rosciani",
  "Necochea",
  "Nicacia Magan de Bouzada",
  "Nicolás Patrón",
  "Nicolás Rojas Acosta",
  "Nicolás Roldán",
  "Nikola Tesla",
  "Nueva Pompeya",
  "O'Higgins",
  "Olaf With",
  "Olegario Víctor Andrade",
  "Oscar Alfredo Gálvez",
  "Oscar Cabalén",
  "Oso Hormiguero",
  "Paaje Doctor Juan Diego De Morgan",
  "Pablo Castalbert",
  "Paciencia",
  "Padre Cerqueira",
  "Padre Distorto",
  "Padre J. Nicolau",
  "Padre Mujica",
  "Padre Sena",
  "Padre Tomás García",
  "Pago de Areco",
  "Pala Pala",
  "Palo Santo",
  "Pampa del Indio",
  "Pampero",
  "Panamá",
  "Paraíso",
  "Pasaje 25 de Mayo",
  "Pasaje 33",
  "Pasaje 9 de Julio",
  "Pasaje Agrimensor Agustín Foster",
  "Pasaje Aguará Guazú",
  "Pasaje Agustín Andreani",
  "Pasaje Alberdi",
  "Pasaje Alberto Torres",
  "Pasaje Andreani",
  "Pasaje Antequeras",
  "Pasaje Antonio Martina",
  "Pasaje Arazá",
  "Pasaje Arbo y Blanco",
  "Pasaje Armando Anello",
  "Pasaje Arminda Rogiolo",
  "Pasaje Arribálzaga",
  "Pasaje Arturo Frondizi",
  "Pasaje Arturo Illia",
  "Pasaje Arturo Lestani",
  "Pasaje Asunción",
  "Pasaje Atilio López",
  "Pasaje Avellaneda",
  "Pasaje Bagual",
  "Pasaje Baltasar Tatalo Domínguez",
  "Pasaje Bariloche",
  "Pasaje Bartolina Sisa",
  "Pasaje Belén",
  "Pasaje Bibiano Meza",
  "Pasaje Brasilia",
  "Pasaje Brown",
  "Pasaje Calle 26",
  "Pasaje Cangallo",
  "Pasaje Capataz Codutti",
  "Pasaje Capitán Eliseo Muñiz",
  "Pasaje Caracas",
  "Pasaje Carlos Boggio",
  "Pasaje Carlos Dodero",
  "Pasaje Carlos Hardy",
  "Pasaje Castelli",
  "Pasaje Catamarca",
  "Pasaje Cataratas del Iguazú",
  "Pasaje Centenario",
  "Pasaje Chaco",
  "Pasaje Charata",
  "Pasaje Ciervo de los Pantanos",
  "Pasaje Cocomarola",
  "Pasaje Colón",
  "Pasaje Coronel Falcon",
  "Pasaje Coronel Ávalos",
  "Pasaje Corrientes",
  "Pasaje Crisanto Domínguez",
  "Pasaje Cuba",
  "Pasaje Córdoba",
  "Pasaje Deschutter",
  "Pasaje Discépolo",
  "Pasaje Doctor Diego de Morgan",
  "Pasaje Doctor Juan Diego de Morgan",
  "Pasaje Duvivier",
  "Pasaje Dónovan",
  "Pasaje Echeverría",
  "Pasaje El Malón",
  "Pasaje El Salvador",
  "Pasaje Ernesto Duvivier",
  "Pasaje Escondido",
  "Pasaje Esperanza",
  "Pasaje Etcheverrigaray",
  "Pasaje Evaristo Ramírez",
  "Pasaje Ex Combatiente E. Discépolo",
  "Pasaje Fabriciano Gómez",
  "Pasaje Felipe Molina",
  "Pasaje Florida",
  "Pasaje Fontana",
  "Pasaje Fortin Aguilar",
  "Pasaje Fortín Aguilar",
  "Pasaje Fortín Alvarado",
  "Pasaje Fortín Loma Negra",
  "Pasaje Fortín Los Pozos",
  "Pasaje Fortín Rivadavia",
  "Pasaje Fortín Tapenagá",
  "Pasaje Fortín Warnes",
  "Pasaje Foster",
  "Pasaje Franklin",
  "Pasaje Fray Bertaca",
  "Pasaje Fray Gabriel Grotti",
  "Pasaje Fray Luis Beltrán",
  "Pasaje Fray Rossi",
  "Pasaje French",
  "Pasaje Félix Codutti",
  "Pasaje General Fotheringam",
  "Pasaje General Pinedo",
  "Pasaje Gerardo Varela",
  "Pasaje Gertrudis Medeiros",
  "Pasaje Gobernador Bosch",
  "Pasaje Gobernador Gabriel Carrasco",
  "Pasaje Guatemala",
  "Pasaje Guerrero",
  "Pasaje Gusberti",
  "Pasaje Güemes",
  "Pasaje H. Saling",
  "Pasaje Haiti",
  "Pasaje Haití",
  "Pasaje Heraclio Pérez",
  "Pasaje Hermanos Boronat",
  "Pasaje Hermanos Palotinos",
  "Pasaje Hernandarias",
  "Pasaje Hipólito Yrigoyen",
  "Pasaje Honduras",
  "Pasaje Ingeniero Augusto Schur",
  "Pasaje Ingeniero Schur",
  "Pasaje Inspector Patiño",
  "Pasaje Intendente Borrini",
  "Pasaje Irene B. de Etcheverrygaray",
  "Pasaje Isla del Cerrito",
  "Pasaje Italia",
  "Pasaje Jeremías",
  "Pasaje Jericó",
  "Pasaje José Alsina",
  "Pasaje José Ameri",
  "Pasaje José Anello",
  "Pasaje José María Paz",
  "Pasaje José María Toledo",
  "Pasaje José Mármol",
  "Pasaje José Navarro",
  "Pasaje José Rucci",
  "Pasaje Juan B. Justo",
  "Pasaje Juan Manuel Rossi",
  "Pasaje Juan Moro",
  "Pasaje Juan XXIII",
  "Pasaje Juan de Dios Mena",
  "Pasaje Juana Moro",
  "Pasaje Jujuy",
  "Pasaje Julio Argentino Roca",
  "Pasaje Julio E. Acosta",
  "Pasaje Julio Tort",
  "Pasaje La Paz",
  "Pasaje La Rioja",
  "Pasaje La Sabana",
  "Pasaje La Tigra",
  "Pasaje Laguna del Desierto",
  "Pasaje Las Heras",
  "Pasaje Lavalle",
  "Pasaje Leandro N. Alem",
  "Pasaje Leo Parzianello",
  "Pasaje Lidia Angélica Rapazzioli de Bernal",
  "Pasaje Lima",
  "Pasaje Liniers",
  "Pasaje Lino Torres",
  "Pasaje Lisandro de la Torre",
  "Pasaje Los Colonizadores",
  "Pasaje Los Hacheros",
  "Pasaje Luis Stando",
  "Pasaje López Piacentini",
  "Pasaje López y Planes",
  "Pasaje M. Varela",
  "Pasaje Machagai",
  "Pasaje Mansilla",
  "Pasaje Manuel Belgrano",
  "Pasaje Manuel Peralta",
  "Pasaje Marcelo Torcuato de Alvear",
  "Pasaje Marcos Paz",
  "Pasaje Margarita Belén",
  "Pasaje Mario Bandeo",
  "Pasaje Mario Villalva",
  "Pasaje Martina",
  "Pasaje Martín Goitía",
  "Pasaje María Moisán",
  "Pasaje Mendoza",
  "Pasaje Miguel Giménez",
  "Pasaje Miguel Z. Delfino",
  "Pasaje Misionero Francisco Solano",
  "Pasaje Molina",
  "Pasaje Montevideo",
  "Pasaje Nazareno Rosciani",
  "Pasaje Necochea",
  "Pasaje Nicaragua",
  "Pasaje Nicolás Rojas Acosta",
  "Pasaje Nicolás Roldán",
  "Pasaje Obligado",
  "Pasaje Ombú",
  "Pasaje Oscar Cabalén",
  "Pasaje Padre Sena",
  "Pasaje Palamedi",
  "Pasaje Panamá",
  "Pasaje Parodi",
  "Pasaje Paso de la Patria",
  "Pasaje Peatonal F. Planes",
  "Pasaje Peatonal General Ortiz",
  "Pasaje Peatonal Hipólito Vieytes",
  "Pasaje Peatonal J. P. Aguirre",
  "Pasaje Peatonal J. R. Balcarce",
  "Pasaje Peatonal Pringles",
  "Pasaje Pellegrini",
  "Pasaje Piñero",
  "Pasaje Posadas",
  "Pasaje Pueyrredón",
  "Pasaje Quito",
  "Pasaje Ramón Vázquez",
  "Pasaje Ramón de las Mercedes Tissera",
  "Pasaje Remedios de Escalada",
  "Pasaje Rene James Sotelo",
  "Pasaje República Dominicana",
  "Pasaje Rioja",
  "Pasaje Rita Waisman",
  "Pasaje Roberto Mora",
  "Pasaje Rodríguez Peña",
  "Pasaje Roger Balet",
  "Pasaje Roque Sáenz Peña",
  "Pasaje Río Negro",
  "Pasaje Saling",
  "Pasaje Salta",
  "Pasaje San Buenaventura del Monte Alto",
  "Pasaje San Carlos de Bariloche",
  "Pasaje San Fernando",
  "Pasaje San Juan",
  "Pasaje San Lorenzo",
  "Pasaje San Martín",
  "Pasaje San Salvador",
  "Pasaje Sanchís",
  "Pasaje Santa Fe",
  "Pasaje Santa María de Oro",
  "Pasaje Sargento Cabral",
  "Pasaje Sargento Discépolo",
  "Pasaje Seelstrang",
  "Pasaje Seitor",
  "Pasaje Sicas",
  "Pasaje Sierras de Córdoba",
  "Pasaje Silvano Dante",
  "Pasaje Simeón Borda",
  "Pasaje Sol de Esperanza",
  "Pasaje Taco Pozo",
  "Pasaje Tambor de Tacuarí",
  "Pasaje Tapir",
  "Pasaje Tatú Carreta",
  "Pasaje Uriburu",
  "Pasaje Urquiza",
  "Pasaje Ushuaia",
  "Pasaje Uspallata",
  "Pasaje Vecinal A. González Balcarce",
  "Pasaje Vecinal Díaz Vélez",
  "Pasaje Vecinal Fray C. Rodríguez",
  "Pasaje Vecinal I. Álvarez Toma",
  "Pasaje Vecinal J. J. Viamonte",
  "Pasaje Vecinal J. M. Dorrego",
  "Pasaje Vecinal J. P. Aguirre",
  "Pasaje Vecinal J. V. de Olavarría",
  "Pasaje Vecinal M. Rodríguez",
  "Pasaje Vecinal Miguel Soler",
  "Pasaje Vecinal Perdriel",
  "Pasaje Vedia",
  "Pasaje Vilallave de Ross",
  "Pasaje Villa Carlos Paz",
  "Pasaje Virtud",
  "Pasaje Viuda de Ross",
  "Pasaje Vélez Sársfield",
  "Pasaje Wilde",
  "Pasaje Yaguareté",
  "Pasaje Yolanda P. de Elizondo",
  "Pasaje Zacarías",
  "Pasaje Zapico",
  "Pasaje de los Patos",
  "Pasaje del Teatro",
  "Pasaje peatonal J. F. Terrada",
  "Pasaje peatonal Padre J. B. Grela",
  "Pasaje Ángel Bustos",
  "Pasaje Ángel D'Ambra",
  "Pasaje Ángel Ibarra",
  "Pasaje Ángela C. de Bouvier",
  "Pasaje Ávalos",
  "Pasaje Édison",
  "Paseo Costanero del Río Negro",
  "Pasillo Ex Vías del Ferrocarril Santa Fe",
  "Paso de la Patria",
  "Peatonal Armada Argentina",
  "Peatonal Bahía Agradable",
  "Peatonal Bahía San Felipe",
  "Peatonal Bahía San Julián",
  "Peatonal Bahía Santa Eufemia",
  "Peatonal Bahía de Ruiz Puent",
  "Peatonal Bahía de San Francisco",
  "Peatonal Bahía de la Anunciación",
  "Peatonal Bahía de la Cruzada",
  "Peatonal Cabo Corrientes",
  "Peatonal Canal Colón",
  "Peatonal Crucero Belgrano",
  "Peatonal Dos Lomas",
  "Peatonal Ejército Argentino",
  "Peatonal Ensenada del Norte",
  "Peatonal Estrecho de San Carlos",
  "Peatonal Gaucho Rivero",
  "Peatonal Isla Culebra",
  "Peatonal Isla Goicoechea",
  "Peatonal Isla Los Hermanos",
  "Peatonal Isla Pan de Azúcar",
  "Peatonal Isla Pelada",
  "Peatonal Isla Remolinos",
  "Peatonal Isla San Jorge",
  "Peatonal Isla Soledad",
  "Peatonal Isla Vigía",
  "Peatonal Isla de Borbón",
  "Peatonal Isla del Pasaje",
  "Peatonal Juan Domingo Perón",
  "Peatonal Nueve de Julio",
  "Peatonal Operación Cóndor",
  "Peatonal Pucará",
  "Peatonal Puente Pacheco",
  "Peatonal Puerto Argentino",
  "Peatonal Soldado J. C. Ávalos",
  "Pedro Freschi",
  "Pedro Olazábal",
  "Pellegrini",
  "Pereyra",
  "Pericón",
  "Perímetro Aeropuerto de Resistencia",
  "Perú",
  "Piedras",
  "Pilagá",
  "Policía de Territorios",
  "Posadas",
  "Primera Junta",
  "Primero de Mayo",
  "Profesor Alejandro Portela",
  "Puente San Fernando",
  "Puente peatonal",
  "Puerto Palos",
  "Puerto Tirol",
  "Puerto Vélaz",
  "Pueyrredón",
  "Pureza",
  "Pío XII",
  "Quebracho",
  "Quitilipi",
  "Quito",
  "R. E. Gorebert",
  "Rafael Obligado",
  "Rampa",
  "Rampa de acceso",
  "Ramón Castilla",
  "Ramón Castro",
  "Ramón Vázquez",
  "Ramón de las Mercedes Tissera",
  "Rancho Porá",
  "Raúl B. Díaz",
  "Remedios de Escalada",
  "Remigio Borque",
  "Rene James Sotelo",
  "René James Sotelo",
  "República Dominicana",
  "República de Israel",
  "Riacho Carolí",
  "Riacho Iné",
  "Ricardo López Jordán",
  "Ricardo Rojas",
  "Rita Agote de Sustaita",
  "Rita Waisman",
  "Roberto Mora",
  "Rodolfo Gabardini",
  "Roger Balet",
  "Roque Sáenz Peña",
  "Rosa Címbaro",
  "Rosa Guarú",
  "Rotonda Italia y Rissione",
  "Rotonda Las Heras y Castelli",
  "Rotonda Nicolás Avellaneda y Sabín",
  "Rotonda de Villa Monona",
  "Rubén Di Palma",
  "Ruta Nacional 11",
  "Río Guaycurú",
  "Río Negro",
  "Río Tapenagá",
  "Río Tatané",
  "Río Teuco",
  "Río Tragadero",
  "Río de Oro",
  "Saavedra",
  "Salta",
  "Samuhú",
  "San Andrés",
  "San Bartolomé",
  "San Bernardo",
  "San Buenaventura del Monte Alto",
  "San Carlos de Bariloche",
  "San Felipe",
  "San Fernando",
  "San Francisco Solano",
  "San Juan",
  "San Judas Tadeo",
  "San Lorenzo",
  "San Luis",
  "San Mateo",
  "San Matías",
  "San Pablo",
  "San Pedro",
  "San Roque",
  "San Salvador",
  "San Simón",
  "Santa Clara de Asís",
  "Santa Cruz",
  "Santa Fe",
  "Santa María de Oro",
  "Santa Sylvina",
  "Santiago Apóstol",
  "Santiago de Liniers",
  "Santiago del Estero",
  "Santo Tomás",
  "Santo Tomé",
  "Sargento Cabral",
  "Saúl Ubaldini",
  "Seitor",
  "Senda",
  "Senda peatonal",
  "Sicas",
  "Sierras de Córdoba",
  "Silvano Dante",
  "Simeón Borda",
  "Simón Bolívar",
  "Sixto Laconich",
  "Soldado Aguilera",
  "Soldado Almonacid",
  "Soraida Áucar",
  "Sudestada",
  "Suiza",
  "Taco Pozo",
  "Tacuarí",
  "Tapir",
  "Tatú Carreta",
  "Teniente Mayor Origone",
  "Teodoro Fels",
  "Thomas Jefferson",
  "Tierra del Fuego",
  "Toba",
  "Tomás Arce",
  "Torcaza",
  "Tordo",
  "Tres Carabelas",
  "Triunfo",
  "Triunvirato",
  "Tránsito Cocomarola",
  "Tucán",
  "Tuyutí",
  "Uriburu",
  "Uruguay",
  "Urunday",
  "Ushuaia",
  "Valdepeñas",
  "Valle de la Luna",
  "Veinte de Junio",
  "Venezuela",
  "Verdad",
  "Viceomodoro Olezza",
  "Victoria Ocampo",
  "Victorio Pereyra",
  "Viento Norte",
  "Villa Berthet",
  "Villa Carlos Paz",
  "Villa Río Bermejito",
  "Villa Ángela",
  "Viraró",
  "Virgen del Valle",
  "Virgilio Mira",
  "Víctor Benítez",
  "Wilde",
  "Yaguareté",
  "Yolanda P. de Elizondo",
  "Zacarías",
  "Zamba",
  "Zonda",
  "Zorzal",
  "tierr",
  "Álvarez Jonte",
  "Ángel Busto",
  "Ángel D'Ambra",
  "Ángel Vicente Peñaloza",
  "Ángela C. de Bouvier",
  "Ástor Piazzolla",
];
export const callesCorrientes = [
  '"""Yacaré"" Aguirre"',
  "11 de Mayo",
  "13 de Junio",
  "16 de agosto",
  "17 De Octubre",
  "18 de Mayo",
  "19 de Mayo",
  "2 de Abril",
  "2 de julio",
  "20 de Mayo",
  "22 de Mayo",
  "24 de Agosto",
  "24 de Mayo",
  "25 de Mayo",
  "3 de Febrero",
  "6 de Mayo",
  "828",
  "832",
  "836",
  "850",
  "857",
  "859",
  "9 de Julio",
  "A. Capdevila",
  "A. Carlos Meza Marengo",
  "A. Lamarque",
  "Abelardo Héctor Dimotta",
  "Abraham Blugerman",
  "Abrevadero",
  "Acceso Av Independencia",
  "Acceso Av independencia",
  "Acceso Escuela Agropecuaria",
  "Acesso Av Independencia",
  "Aconcagua",
  "Aconquija",
  "Acuña Juan José",
  "Adolfo Bioy Casares",
  "Adolfo Cipriano (Fito) Ledesma",
  "Adolfo Mors",
  "Agr. Domingo Tassano",
  "Agr. Domingo Tassano (114)",
  "Agr. Miguel Ángel Rojas (115)",
  "Aguapey",
  "Aguará Guazú",
  "Aguaí",
  "Agustin Maza",
  "Agustín Donado",
  "Agustín Justo",
  "Agustín Lara",
  "Agustín Ontiveros",
  "Agutí",
  "Alberto Devoto",
  "Alcaraz",
  "Alcidez Córdoba",
  "Alecrin",
  "Alejandro Barrios",
  "Alejandro Dumas",
  "Alejandro Gallardo",
  "Alejandría",
  "Alejo Ceballos",
  "Alfonsina Storni",
  "Alfredo Bufano",
  "Alfredo Rubén Velásquez (109)",
  "Almirante Brown",
  "Alta Gracia",
  "Alvear",
  "Amado Bompland",
  "Amado Bondplan",
  "Amado Puyau",
  "Amanda Etcheguren",
  "Amarilla Hipólito Jorge Daniel",
  "Amazonas",
  "Ambay",
  "Ambrosetti",
  "Américo Vespucio",
  "Andalucía",
  "Antequeras",
  "Antonio Ballerini",
  "Antonio María Díaz",
  "Antonio Nariño",
  "Antonio Sáenz",
  "Aperea",
  "Arcelio Esteban Lezcano",
  "Arenales",
  "Argentina",
  "Argentina Rojas",
  "Argerich",
  "Aristóbulo del Valle",
  "Armando Nelli",
  "Arq. Miguel Rojas",
  "Arturo de Carranza",
  "Australia",
  "Av Chacabuco",
  "Av. Ayacucho",
  "Ave María",
  "Avenida 3 de Abril",
  "Avenida Alberdi",
  "Avenida Argentina Rojas",
  "Avenida Armando Romero",
  "Avenida Armando Romero (Ruta Provincial 5)",
  "Avenida Armenia",
  "Avenida Artigas",
  "Avenida Ayacucho",
  "Avenida Cangallo",
  "Avenida Cazadores Correntinos",
  "Avenida Centenario",
  "Avenida Chacabuco",
  "Avenida Colón",
  "Avenida Costanera General San Martín",
  "Avenida Costanera Juan Pablo II",
  "Avenida Cruz del Sud",
  "Avenida Doctor Jorge Manuel Romero",
  "Avenida El Maestro",
  "Avenida Eva Perón",
  "Avenida Eva Perón (ex Río Chico)",
  "Avenida Federico Laprida",
  "Avenida Francisco Narciso Laprida",
  "Avenida Gobernador Juan Pujol",
  "Avenida Gobernador Ruiz",
  "Avenida Iberá",
  "Avenida Independencia",
  "Avenida Italia",
  "Avenida José Manuel Estrada",
  "Avenida Juan Ramón Fernández",
  "Avenida Juan Ramón Vidal",
  "Avenida La Paz",
  "Avenida Libertad",
  "Avenida Maipú",
  "Avenida Medrano",
  "Avenida Patagonia",
  "Avenida Paysandú",
  "Avenida Pedro Celestino Montenegro",
  "Avenida Pedro Ferré",
  "Avenida Pomar",
  "Avenida Presidente Arturo Frondizi",
  "Avenida Presidente Doctor Raúl Alfonsín",
  "Avenida Raúl Alfonsín",
  "Avenida René Favaloro",
  "Avenida Río Chico",
  "Avenida Santa Catalina",
  "Avenida Santa Rosa",
  "Avenida Sarmiento",
  "Avenida Teniente Ibáñez",
  "Avenida del IV Centenario",
  "Aviador José Correa Fernández",
  "Azcuénaga",
  "Badajoz",
  "Barakaldo",
  "Barcelona",
  "Bariloche",
  "Bartolomé Hidalgo",
  "Basavilbaso",
  "Belgrano",
  "Belisario Roldán",
  "Belisario Tiscornia",
  "Bella Vista",
  "Benavídez",
  "Benito Lynch",
  "Berazategui",
  "Bernardino López",
  "Beruti",
  "Bilbao",
  "Blas Benjamín de la Vega",
  "Blas Martinez Riera",
  "Blas Parera",
  "Bolivia",
  "Bolívar",
  "Bordón Héctor Ramón",
  "Boston",
  "Boutron Ruben Isidoro",
  "Brasil",
  "Buenos Aires",
  "Bélgica",
  "Caa Cati",
  "Caa Guazú",
  "Cabildo",
  "Cabo Roque Evaristo Sánchez",
  "Cabo de Hornos",
  "Cafayate",
  "California",
  "Calingasta",
  "Callao",
  "Calle 1",
  "Calle 1029",
  "Calle 1046",
  "Calle 106",
  "Calle 11",
  "Calle 111",
  "Calle 113",
  "Calle 115",
  "Calle 117",
  "Calle 118",
  "Calle 119",
  "Calle 1219",
  "Calle 122",
  "Calle 1220",
  "Calle 1221",
  "Calle 1222",
  "Calle 1223",
  "Calle 136",
  "Calle 138",
  "Calle 146",
  "Calle 147",
  "Calle 149",
  "Calle 154",
  "Calle 156",
  "Calle 160",
  "Calle 171",
  "Calle 172",
  "Calle 173",
  "Calle 175",
  "Calle 177",
  "Calle 2",
  "Calle 206",
  "Calle 212",
  "Calle 214",
  "Calle 230",
  "Calle 259",
  "Calle 261",
  "Calle 273",
  "Calle 3",
  "Calle 302",
  "Calle 304",
  "Calle 32",
  "Calle 337",
  "Calle 341",
  "Calle 394",
  "Calle 396",
  "Calle 398",
  "Calle 4",
  "Calle 400",
  "Calle 403",
  "Calle 415",
  "Calle 420",
  "Calle 421",
  "Calle 422",
  "Calle 424",
  "Calle 427",
  "Calle 444",
  "Calle 445",
  "Calle 459",
  "Calle 467",
  "Calle 481",
  "Calle 492",
  "Calle 494",
  "Calle 5",
  "Calle 507",
  "Calle 508",
  "Calle 509",
  "Calle 511",
  "Calle 514",
  "Calle 515",
  "Calle 555",
  "Calle 577",
  "Calle 579",
  "Calle 6",
  "Calle 621",
  "Calle 66",
  "Calle 66-1",
  "Calle 66-5",
  "Calle 7",
  "Calle 703",
  "Calle 717",
  "Calle 722",
  "Calle 725",
  "Calle 726",
  "Calle 733",
  "Calle 741",
  "Calle 750",
  "Calle 754",
  "Calle 756",
  "Calle 760",
  "Calle 761",
  "Calle 8",
  "Calle 803",
  "Calle 805",
  "Calle 811",
  "Calle 83-2",
  "Calle 83-4",
  "Calle 838",
  "Calle 842",
  "Calle 843",
  "Calle 844",
  "Calle 845",
  "Calle 846",
  "Calle 847",
  "Calle 85",
  "Calle 850",
  "Calle 860",
  "Calle 865",
  "Calle 867",
  "Calle 868",
  "Calle 871",
  "Calle 872",
  "Calle 873",
  "Calle 874",
  "Calle 876",
  "Calle 877",
  "Calle 880",
  "Calle 890",
  "Calle 9",
  "Calle 903",
  "Calle 930",
  "Calle 931",
  "Calle 933",
  "Camba Punta",
  "Canadá",
  "Cancharana",
  "Cangallo",
  "Canteros",
  "Capibara",
  "Capilla del Monte",
  "Capitán José Leónidas Ardiles",
  "Capitán L. Guadanini",
  "Capitán Manuel Oscar Bustos",
  "Caracas",
  "Caraya",
  "Caribe",
  "Carlos A. Moratorio (113)",
  "Carlos Alberto Contreras Gómez",
  "Carlos Alberto Frías",
  "Carlos Castellan",
  "Carlos E Castagnino",
  "Carlos E. Castagnino",
  "Carlos Gualberto Meza",
  "Carlos Hugo Medina",
  "Carlos María Vargas Gómez",
  "Carlos Pellegrini",
  "Carlos Pérez Rueda (107)",
  "Carlos R. Marcon",
  "Carlos Saavedra Lamas",
  "Carlos Talavera",
  "Carmelo Fernández",
  "Carmen Ferré de Alsina",
  "Cartagena",
  "Castor de León",
  "Castro Barros",
  "Catamarca",
  "Caá Catí",
  "Cañada de Gómez",
  "Cecilia Alba Mayo de Ingaramo",
  "Cerdeña",
  "Cerrito",
  "Chacabuco",
  "Chaco",
  "Chango Paniagua",
  "Chile",
  "Chubut",
  "Chávez",
  "Ciervo de Los Pantanos",
  "Ciudad de Arequipa",
  "Cnel. Dupuy",
  "Cnel. Wenceslao Martínez",
  "Cochabamba",
  "Cocomarola",
  "Colectora RN 12",
  "Colectora RN12",
  "Colombia",
  "Combate de los Pozos",
  "Comodoro Rivadavia",
  "Concepción Miranda",
  "Concordia",
  "Congreso",
  "Corinto",
  "Cornelio Saavedra",
  "Coronel Artaza",
  "Coronel Santiago Baibiene",
  "Coronel Zapiola",
  "Cosquín",
  "Costanera Norte",
  "Cristo Obrero",
  "Cruz de los Milagros",
  "Cruz del Eje",
  "Cuba",
  "Cura Brochero",
  "Curiyú",
  "Curuzú Cuatiá",
  "Cádiz",
  "César A. Galvaliz Silgueira",
  "César Galvaliz Silgueira",
  "César Álvarez",
  "Córcega",
  "Córdoba",
  "Damasio Esquivel",
  "Daniel Omar Luque",
  "Dardo Rocha",
  "Demetrio Molina",
  "Descartes",
  "Diamante",
  "Diego Ferreyra",
  "Diego de Irala",
  "Dimotta Raúl Horacio",
  "Doctor Alfredo Lanari",
  "Doctor Carlos Benitez",
  "Doctor Esio Ariel Silveira",
  "Doctor José Miguel Guastavino",
  "Doctor Luis Federico Leloir",
  "Doctor Miguel Sussini",
  "Doctor Ramón Carrillo",
  "Doctor Wenceslao Dominguez",
  "Doctor Wenceslao Domínguez",
  "Domingo Lastra",
  "Domingo Matheu",
  "Dominicana",
  "Don Bosco",
  "Don Juan C. Gordiolla Niella",
  "Don Justino Solari",
  "Don Valmiro Ayala Gauna",
  "Dorrego",
  "Doña Carmen Lubary de García",
  "Doña Dolores Vedoya de Molina",
  "Doña Inés Arias de Mancilla",
  "Doña Josefa Derqui de Díaz Colodrero",
  "Doña Mercedes Cremonte",
  "Doña Sinforosa Rolón y Rubio",
  "Doña Ángela Iglesia de Llano",
  "Dpto. Mercedes",
  "Dr. Antonio Marottolli",
  "Dr. Antonio Ramón Terraes",
  "Dr. Clemente Maldonado",
  "Dr. Diocles Alfredo Isidoro Revidatti",
  "Dr. Enrique Jasid",
  "Dr. Ernesto Meabe",
  "Dr. Felipe G. Fages",
  "Dr. H. Unanue",
  "Dr. Higinio P. Schiffo",
  "Dr. J. F. Muñíz",
  "Dr. José Colombres",
  "Dr. José Miguel Guastavino",
  "Dr. Luis Federico Leloir",
  "Dr. Manuel Gonzalez",
  "Dr. Miguel Sussini",
  "Dr. Pedro Alberto Correa",
  "Dr. Ramón Carrillo",
  "Dr. Ramón Contreras",
  "Dr. Vargas Gómez",
  "Dr. Wenceslao Domínguez",
  "Dávalos",
  "Díaz de Solís",
  "Díaz de Vivar",
  "E. Larreta",
  "Ecuador",
  "Eduardo Madero",
  "Ejército Argentino",
  "El Ceibo",
  "El Chocon",
  "El Chocón",
  "El Dorado",
  "El Jacarandá",
  "El Libertador",
  "El Mirador",
  "El Sauce",
  "El Trébol",
  "El Urunday",
  "El Ñandubay",
  "Eliseo Corrales",
  "Eliseo Popolizio",
  "Eloisa Chico de Arce",
  "Elías Abad",
  "Emilio Chamorro",
  "Emilio Jose Noya",
  "Empedrado",
  "Enlace a J. R. Fernández",
  "Enlace a calle Chaco",
  "Entrada",
  "Entre Ríos",
  "Ernesto Amadey",
  "Ernesto Romeo Carnevalli",
  "Escocia",
  "Esmeralda",
  "Esparta",
  "España",
  "Espinillo",
  "Espronceda",
  "Estado de Israel",
  "Estados Unidos",
  "Esteban Adolfo Ibáñez",
  "Esteban Bajac",
  "Esteban Laureano Maradona",
  "Esteban de Quirini",
  "Estocolmo",
  "Eugenio Bravo",
  "Eulogio Cabral",
  "Eulogio Nestor Amarilla",
  "Eustaquio Miño",
  "Evaristo Fernández Rudaz",
  "Evaristo González",
  "Ex Combatiente de Malvinas Adolfo Domingo Torres",
  "Ex Combatiente de Malvinas Canteros",
  "Ex Combatiente de Malvinas José Luis Tabares",
  "Ex Teto",
  "Ex Vias General Urquiza",
  "Ex Vías FFCC",
  "Facundo",
  "Facundo Quiroga",
  "Falucho",
  "Federico Roberto Bibiano Palma",
  "Felipe J. B. Lanari Zubiaur",
  "Fernando José Díaz Ulloque",
  "Fernando Pessoa",
  "Fernández Remigio Antonio",
  "Fernández de Moratín",
  "Ferre de Alasino",
  "Finlandia",
  "Fitz Simon",
  "Florencia",
  "Florencio Varela",
  "Florentino Ameghino",
  "Formosa",
  "Fragata Hercules",
  "Fragata La Argentina",
  "Fragata Sarmiento",
  "Francesco Ruiz Mansilla",
  "Francia",
  "Francisco Blasco y Fernández de Moreda",
  "Francisco Manzi (564)",
  "Francisco Pizarro",
  "Francisco Rizzuto",
  "Francisco Romero",
  "Francisco de Balboa",
  "Franklin",
  "Franklin Ruveda",
  "Fray C. Rodríguez",
  "Fray Ignacio María Marti y Porta",
  "Fray Ignacio María Martí y Porta",
  "Fray José de la Quintana",
  "Fray Luis Beltrán",
  "French",
  "Futaleufú",
  "Félix de Azara",
  "Gabino Casco",
  "Gabino Coria Peñaloza",
  "Gabino Ruiz Diaz",
  "Gabriela Mistral",
  "Garcia Antonio Fernando",
  "Garcilazo de la Vega",
  "García de Cossio",
  "Gascón",
  "Gato y Mancha",
  "Gdor. Dr. José R. Gómez",
  "Gdor. Gral. Juan Velazco",
  "Gdor. Ing. V. Virasoro",
  "Gdor. Martínez",
  "Gdor. Piragine Niveyro",
  "General Paz",
  "Gerardo Pisarello",
  "Gobernador Antonio B. Gallino",
  "Gobernador Doctor Contte",
  "Gobernador Evaristo López",
  "Gobernador Felipe Cabral",
  "Gobernador Gelabert",
  "Gobernador González",
  "Gobernador José Gómez",
  "Gobernador José Manuel Pampín",
  "Gobernador José María Rolón",
  "Gobernador Juan Vicente Pampín",
  "Gobernador Loza",
  "Gobernador Manuel I. Lagraña",
  "Gobernador Martín Goitia",
  "Gobernador Martínez",
  "Gobernador Miguel Gelabert",
  "Gobernador Robert",
  "Gobernador Soto",
  "Gobernador Torrent",
  "Godoy Cruz",
  "Gorostiaga",
  "Gorriti",
  "Goya",
  "Gral. Joaquín de Madariaga",
  "Gral. Paunero",
  "Granada",
  "Grecia",
  "Gregorio de Laferrere",
  "Guadalajara",
  "Guaiquiraró",
  "Gualeguaychú",
  "Guatemala",
  "Guayaibí",
  "Guayanas",
  "Guayaquil",
  "Guayquiraró",
  "Guazuncho",
  "Guido Spano",
  "Guillermo Nuñez",
  "Guillermo Rawson",
  "Guillermo Raúl Ojeda",
  "Guipúzcoa",
  "Gunitsky",
  "Gustavo Martínez Zubiria",
  "Gutenberg",
  "Gutnisky",
  "Gómez Mario",
  "Güemes",
  "Haití",
  "Hatillo - Barbosa",
  "Hawai",
  "Heraclio Pérez",
  "Hermanos Barrios",
  "Herminio Gimenez",
  "Hernandarias",
  "Hernán Cortéz",
  "Hernán Félix Gómez",
  "Heroes de Malvinas (Olmedo)",
  "Hipólito Jorge Daniel Amarilla",
  "Hipólito Yrigoyen",
  "Honduras",
  "Horacio Quiroga",
  "Hortencio Quijano",
  "Houssay",
  "Humahuaca",
  "Hungría",
  "Héctor José Boo",
  "Héroes Civiles",
  "Héroes de Malvinas (Olmedo)",
  "Iberá",
  "Incienso",
  "Indonesia",
  "Ing. Elisa B. Bachofen",
  "Ing. Jean Courbon",
  "Ing. Manuel E. Gómez Vara (111)",
  "Ing. Prilidiano Pueyrredon (112)",
  "Inglaterra",
  "Int. Luis Belascoain",
  "Irineo Osvaldo Maciel",
  "Islas Baleares",
  "Ismael Grosso",
  "Ita Ibaté",
  "Ituzaingó",
  "Itá Ibaté",
  "J. Alfredo Ferreyra",
  "J. J. Vallejos",
  "Jaime Mazza",
  "Jaime Viudes",
  "Jamaica",
  "Jardín Correntino",
  "Jaribú",
  "Javier María Reparaz",
  "Jazmín",
  "Joaquin Arqueros",
  "Joaquín García",
  "Joaquín Sheridan",
  "Johnny Berh",
  "Jorge Amado",
  "Jorge Atlántico Rodriguez",
  "Jorge Badaracco",
  "Jorge Benchetrit Medina",
  "Jorge Isaac",
  "Jose Hernandez",
  "Jose Ingenieros",
  "Josefina Contte",
  "José Aguirre",
  "José Alberto Mendez",
  "José Conte",
  "José Darragueira",
  "José Figueroa Alcorta",
  "José Hernández",
  "José Ignacio Añasco",
  "José Luciano Romero",
  "José M. Aguirre",
  "José Malabia",
  "José Mariano Serrano",
  "José Marmol",
  "José Martí",
  "José Morelos",
  "José Mármol",
  "José Negro",
  "José Nicolás Alsina (552)",
  "José Niella",
  "José Pacheco de Melo",
  "José Plotnicoff",
  "José Ramón Ferrau",
  "José Ramón Vidal",
  "José Sasson",
  "José T. González Vedoya",
  "José Thames",
  "José Thelier",
  "José Valpuesta",
  "José de Olavarría",
  "Juan Andrés Silva",
  "Juan Armando Guidobono",
  "Juan Bautista Alberdi",
  "Juan Carlos Luis Semper",
  "Juan Coll",
  "Juan De Garay",
  "Juan José Acuña",
  "Juan José Castelli",
  "Juan José Lubary",
  "Juan José Paso",
  "Juan José Viamonte",
  "Juan Kepler",
  "Juan M. Pueyrredon",
  "Juan Manuel de Rosas",
  "Juan Ortíz de Zárate",
  "Juan Pablo I",
  "Juan Pablo II",
  '"Juan Pedro ""Quique"" Sorribes"',
  "Juan R. Rojas",
  "Juan Ramón Giménez",
  "Juan Raúl Serradori",
  "Juan Romero",
  "Juan Sebastián Elcano",
  "Juan Serrano",
  "Juan Simón Sánchez",
  "Juan Tomás Meza",
  "Juan Torres de Vera y Aragón",
  "Juan Vucetich",
  "Juan de Ayolas",
  "Juan de Dios Gómez",
  "Juan de Garay",
  "Juana de Ibarbourou",
  "Juancito el Peregrino",
  "Jujuy",
  "Julio Antonio Cardozo",
  "Julio Cortázar",
  "Julio Domingo Civetta",
  "Julio Montes",
  "Julio Vedia",
  "Julio Verne",
  "Junín",
  "Kepler",
  "Klein Segismundo",
  "La Bajada Araña",
  "La Cruz",
  "La Hortencia",
  "La Pampa",
  "La Rioja",
  "Lamadrid",
  "Lapacho",
  "Lapurdi",
  "Larrea",
  "Las Amapolas",
  "Las Azaleas",
  "Las Azucenas",
  "Las Caléndulas",
  "Las Camelias",
  "Las Carmelias",
  "Las Cuevas",
  "Las Dalias",
  "Las Dalias Norte",
  "Las Dalias Sur",
  "Las Gardenias",
  "Las Heras",
  "Las Hortencias",
  "Las Margaritas",
  "Las Margaritas Norte",
  "Las Orquídeas",
  "Las Pasionarias",
  "Las Piedras",
  "Las Rosas",
  "Las Teresitas",
  "Las Violetas",
  "Las Violetas Norte",
  "Lavalle",
  "Leandro Alem",
  "Leopoldo Lugones",
  "Leopoldo Marechal",
  "Lezcano Arcelio Esteban",
  "Limite Barrio San Antonio / San Roque",
  "Limite Barrio San Jorge / Serantes",
  "Limite Barrios",
  "Limite barrio ongay",
  "Limites Barrios",
  "Limites de Barrios",
  "Linares",
  "Lisandro Segovia",
  "Lisboa",
  "Lobito de Río",
  "Lomas",
  "Lorenzo Gabriel Toledo",
  "Loreto",
  "Los Abuelos",
  "Los Alamos",
  "Los Alelíes",
  "Los Alpes",
  "Los Andes",
  "Los Araucanos",
  "Los Artesanos",
  "Los Atacamas",
  "Los Calchaquies",
  "Los Charruas",
  "Los Claveles",
  "Los Cocos",
  "Los Comechingones",
  "Los Crisantemos",
  "Los Cóndores",
  "Los Fresnos",
  "Los Girasoles",
  "Los Gladiolos",
  "Los Guaraníes",
  "Los Laureles",
  "Los Lirios",
  "Los Malvones",
  "Los Matacos",
  "Los Onas",
  "Los Puelches",
  "Los Teheuelches",
  "Los Tehuelches",
  "Los Tilos",
  "Los Tobas",
  "Los Tulipanes",
  "Los Álamos",
  "Lucía Soto",
  '"Luis ""Mojarrita"" Agüero"',
  "Luis Braille",
  "Luis Ferreyra (Juan Paye)",
  "Luis María Babin",
  "Luis Navarrete",
  "Luján",
  "Lunita del Taragüí",
  "Luzuriaga",
  "Lyon",
  "M. de Cabrera",
  "Madariaga",
  "Madre Teresa de Calcuta",
  "Madrid",
  "Magallanes",
  "Malta",
  "Malvinas Argentinas",
  "Managua",
  "Manantiales",
  "Manuel Acevedo",
  "Manuel Alberti",
  "Manuel Mujica Lainez",
  "Manuel Puig",
  "Manuel Vicente Figuerero (558)",
  "Mar de Ajó",
  "Mar del Plata",
  "Maracaibo",
  "Marcelo Breard",
  "Marcelo de la Torre",
  "Marcos Sastre",
  "Margarita Kofman de Shvetz (560)",
  "Maria Teresa Villone",
  "Mariano A. Igarzabal",
  "Mariano Boedo",
  "Mariano Cadenas",
  "Marili Morales Segovia",
  '"Mario ""Chaque"" Mauriño"',
  "Mario Bofill",
  "Mario Gómez",
  "Mario Jose Payes",
  "Mario José Payes",
  "Mario Millan Medina",
  "Mario de Jesús Insaurralde",
  "Marsella",
  "Martin Fierro",
  "María Edith Davila de Soto",
  "Matheu",
  "Matias Pipet",
  "Mbiguá",
  "Mburucuyá",
  "Medalla Milagrosa",
  "Medina Carlos Hugo",
  "Medrano",
  "Mendoza",
  "Mercedaria",
  "Mercedes Cremonte",
  "Merceditas",
  "Merceditas de San Martín",
  "Mesopotamia",
  "Miami",
  "Michel Sheridan",
  "Miguel Cane",
  "Miguel Villanueva",
  "Miguel del Corro",
  "Miguel Ángel Tasiuk",
  "Milán",
  "Mirta B. Blanco",
  "Misiones",
  "Mocito Acuña",
  "Mocoretá",
  "Monte Caseros",
  "Monteagudo",
  "Montecarlo",
  "Montes de Oca",
  "Moreno",
  "Morse",
  "Mtro. Severo Fernández",
  "Murcia",
  "Málaga",
  "México",
  "Nahuel Huapi",
  "Nazario Benavídez",
  "Necochea",
  "Nelly Vazquez de Moresi",
  "Neuquén",
  "Nevada",
  "Nicanor Molinas",
  "Nicaragua",
  "Nieves Britez",
  "Nini Flores",
  "Nity Cigersa",
  "Niza",
  "Niño Jesús",
  "Normandía",
  "Ntra. Sra. de Lourdes",
  "Nuestra Señora de la Asunción",
  "Nueva Zelanda",
  "Nápoles",
  "Obispo Niella",
  "Odin Fleitas",
  "Olegario Victor Andrade",
  "Olivos",
  "Omar Leiva",
  "Ombú",
  "Orán",
  "Oscar Casco",
  "Oscar Kriskovich Cibils",
  "Osmar Luis González",
  "Osvaldo Meabe",
  "Osvaldo Soriano",
  "Pablo Neruda",
  "Pablo Obregón",
  "Pablo Picasso",
  "Pablo Pizzurno",
  "Pablo VI (91)",
  "Padre Borgatti",
  "Padre Isidro Blanco Vega",
  "Padre Jose Luis Schmidt",
  "Padre Juan Guido Luchell",
  "Padre Julio",
  "Padre Lavagna",
  "Padre Roldán",
  "Pago Largo",
  "Paiubre",
  "Palermo",
  "Palmar Grande",
  "Palmeras",
  "Paraguay",
  "Pasaje 171",
  "Pasaje 349",
  "Pasaje 6",
  "Pasaje Agustín González",
  "Pasaje Antártida Argentina",
  "Pasaje Artigas",
  "Pasaje Atenas",
  "Pasaje Aurora",
  "Pasaje Boston",
  "Pasaje Cabral",
  "Pasaje Campana",
  "Pasaje Candioti",
  "Pasaje Catuegno",
  "Pasaje Chascomús",
  "Pasaje Cortázar",
  "Pasaje Danubio",
  "Pasaje Detroit",
  "Pasaje Fariña",
  "Pasaje Florida",
  "Pasaje Herrera",
  "Pasaje Hugo Asterio Cabral",
  "Pasaje Ibarra",
  "Pasaje Islas Malvinas",
  "Pasaje Islas Orcadas",
  "Pasaje Julio Fridman",
  "Pasaje Juncal",
  "Pasaje Junin",
  "Pasaje La Merced",
  "Pasaje La Rosada",
  "Pasaje Laffont",
  "Pasaje Laplace",
  "Pasaje Mantilla",
  "Pasaje Mitre",
  "Pasaje Morgan",
  "Pasaje Ocanto",
  "Pasaje Ortiz",
  "Pasaje Pedro Bonastre",
  "Pasaje Praga",
  "Pasaje Revidatti",
  "Pasaje Robert",
  "Pasaje Samela",
  "Pasaje San Nicolas",
  "Pasaje Sandra Salguero Cerrullo",
  "Pasaje Sargento Mayor Atienza",
  "Pasaje Saénz",
  "Pasaje Sáenz",
  "Pasaje Temperley",
  "Pasaje Tomás Manuel de Anchorena",
  "Pasaje Trinidad",
  "Pasaje Versalles",
  "Pasaje Vesubio",
  "Pasaje Vieytes",
  "Pasaje Villanueva",
  "Pasaje Virgen María Auxiliadora",
  "Pascual Ruiz Huidobro",
  "Paseo Santa Catalina",
  "Paseo de la Patria Grande",
  "Pasillo 1",
  "Pasillo 2",
  "Pasillo 3",
  "Pasillo Basurita",
  "Pasillo El Olvido",
  "Patagonia",
  "Paul Groussac",
  "Paul Harris",
  "Paula Albarracin",
  "Pedernera",
  '"Pedro ""Pilu"" Gómez"',
  "Pedro Araoz",
  "Pedro Bonifacio Palacios Almafuerte",
  "Pedro Centeno",
  "Pedro Colodrero",
  "Pedro De Ciervi",
  "Pedro Esnaola",
  "Pedro F. Moresi",
  "Pedro J. Leconte Reyna",
  "Pedro Laplace",
  "Pedro León Gallo",
  "Pedro Mendoza",
  "Pedro Pascasio Enriquez",
  "Pedro Quevedo",
  "Pedro Uriarte",
  "Pedro de la Plaza",
  "Pergamino",
  "Perito Moreno",
  "Perpetua María Llano de Rodríguez",
  "Perugorría",
  "Perú",
  "Peteribí",
  "Pio XII",
  "Pirovano",
  "Pitagoras",
  "Pitágoras",
  "Pje. 126",
  "Pje. 179",
  "Pje. 297",
  "Pje. 3 de Mayo",
  "Pje. 361",
  "Pje. 363",
  "Pje. 364",
  "Pje. 4",
  "Pje. 58",
  "Pje. 662",
  "Pje. 739",
  "Pje. 757",
  "Pje. 759",
  "Pje. 76",
  "Pje. 864",
  "Pje. 884",
  "Pje. 885",
  "Pje. 886",
  "Pje. 887",
  "Pje. 888",
  "Pje. Acosta",
  "Pje. Ambay",
  "Pje. Ascasubi",
  "Pje. Ayohuma",
  "Pje. Baradero",
  "Pje. Barranqueras",
  "Pje. Belcastro",
  "Pje. Belén",
  "Pje. Biran",
  "Pje. Birán",
  "Pje. Bover",
  "Pje. Candioti",
  "Pje. Candiotti",
  "Pje. Cantuta",
  "Pje. Castellanos",
  "Pje. Catuegno",
  "Pje. Chascomús",
  "Pje. D'Andrea",
  "Pje. Dante",
  "Pje. Don Gabriel Feris",
  "Pje. Don Jorge Alberto Costas",
  "Pje. Don Orione",
  "Pje. Edelman",
  "Pje. El Cartero",
  "Pje. Francisco Galíndez",
  "Pje. Galarza",
  "Pje. Garrido",
  "Pje. Garruchos",
  "Pje. Gassiebayle",
  "Pje. Granadero",
  "Pje. Groenlandia",
  "Pje. Guardiamarina José Ferré",
  "Pje. Hudson",
  "Pje. Irupé",
  "Pje. Islas Canarias",
  "Pje. Ituzaingó",
  "Pje. Juan A. Gueri",
  "Pje. Juan J. Fernández Blanco",
  "Pje. La Falda",
  "Pje. Las Flores",
  "Pje. Levenne R.",
  "Pje. Linares",
  "Pje. Lincoln",
  "Pje. Londres",
  "Pje. Los Esteros",
  "Pje. Los Ángeles",
  "Pje. Lujambio",
  "Pje. Molina Punta",
  "Pje. Niño Jesús",
  "Pje. Ntra. Sra. de Pompeya",
  "Pje. Nueva Jersey",
  "Pje. Olazábal",
  "Pje. París",
  "Pje. Recova",
  "Pje. Río Luján",
  "Pje. San Nicolás",
  "Pje. Santa Julia",
  "Pje. Sarmiento",
  "Pje. Sgto. Mayor Atienza",
  "Pje. Solari",
  "Pje. Tabare",
  "Pje. Tomás Guido",
  "Pje. Torrent",
  "Pje. Torrent de Torrent",
  "Pje. Virgen del Rosario",
  "Pje. de la Rosa",
  "Pje. Álvarez",
  "Playa Miramar",
  "Plinio Favilla",
  "Plumerillo",
  "Plácido Martínez",
  "Porfirio Antonio Aquino",
  "Posadas",
  "Potosí",
  "Presidente Arturo Illia",
  "Presidente Juan Domingo Perón",
  "Presidente Nicolás Avellaneda",
  "Primera Junta",
  "Pringles",
  "Prof. Carlos I. Goitia",
  "Prof. Carmen Juana Gauna",
  "Prof. Florencio Godoy Cruz",
  "Prof. Nolly Wyngaard de Monzón",
  "Prof. Pedro Crespo",
  "Prof. Pedro Grabre",
  "Profesor Pedro Crespo",
  "Prolong. Guadalajara",
  "Provincias Unidas",
  "Próspero Santillán",
  "Pte. Arturo Illia",
  "Pte. Dr. Arturo Frondizi",
  "Puente Blanco",
  "Puente General Belgrano",
  "Puente Vehicular",
  "Puente Verde",
  "Puente de Madera",
  "Puente de chapa (lata)",
  "Punta Arazaty",
  "Punta Mitre",
  "Punta Mogotes",
  "Punta San Sebastían",
  "Punta Vidal",
  "Punta Ñaro",
  "Punta Ñaró",
  "Pérez Bulnes",
  "Pérez Vicente Ramón",
  "Pío X",
  "Pío XI",
  "Quebracho",
  "Quinquela Martin",
  "Quito",
  "Rafael Barrios",
  "Rafael López",
  "Rafael Obligado",
  "Rafael Rovira Vilellas",
  "Rafaela",
  "Ramos Mejía",
  "Ramón Antonio Meza",
  "Ramón Cirilo Blanco",
  "Ramón Félix Moray",
  "Ramón García",
  "Ramón Sixto Rios",
  "Ramón Tito Aranda",
  "Raúl Alberto Balbastro",
  "Raúl B. Castillo",
  "Raúl Scalabrini Ortiz",
  "Raúl de Labougle",
  "Reconquista",
  "Regimiento de Infantería Nº9",
  "Regimiento de Patricios",
  "Remedios de Escalada",
  "Remigio Antonio Fernández",
  "Renacimiento",
  "René Favaloro",
  "República del Libano",
  "República. Dominicana",
  "Resoagli",
  "Restituto Ortiz",
  "Retorno por J. R. Fernández",
  "Ricardo Gutiérrez",
  "Ricardo Güiraldes",
  "Ricardo J. G. Harvey (562)",
  "Ricardo Rojas",
  "Rio Bermejo",
  "Rio Juramento",
  "Rio Limay",
  "Rito Florencio Portillo",
  "Rivadavia",
  "Roberto Arlt",
  "Roberto Fernando Giusti",
  "Roberto Koch",
  "Roberto Leyes",
  "Roberto Verdun",
  "Roberto Yedro",
  "Roca",
  "Rodríguez Alegre Victor",
  "Rodríguez Andrés Daniel",
  "Rodríguez Peña",
  "Rolón",
  "Roma",
  "Romero",
  "Romilio P. Monzón",
  "Romulo Gregorio Artieda",
  "Roque Evaristo Sánchez",
  "Roque Librado González",
  "Roque Saenz Peña",
  "Rosendo Arias",
  "Rotonda Acceso Avenida Maipú",
  "Rotonda Acceso a Santa Catalina",
  "Rotonda Avenida Juan Ramón Vidal",
  "Ruben Alberto Loreiro",
  "Ruben Dri",
  "Ruben L. Palmeiro",
  "Rubén Alberto Loreiro",
  "Rubén Isidoro Boutron",
  "Rumania",
  "Ruta Nacional 12",
  "Ruta Provincial 46",
  "Ruta Provincial 5",
  "Ruta Provincial 99",
  "Río Bermejo",
  "Río Chico",
  "Río Cuarto",
  "Río Dulce",
  "Río Gallegos",
  "Río Iguazú",
  "Río Miriñay",
  "Río Negro",
  "Río Tercero",
  "Río de Janeiro",
  "Saavedra",
  "Saladas",
  "Salamanca",
  "Salida",
  "Salta",
  "Samohu",
  "Samuel Morse",
  "San Francisco de Asís",
  "San Fransisco de Asís",
  "San Juan",
  "San Lorenzo",
  "San Luis",
  "San Marcelo (110)",
  "San Martín",
  "Sanches de Loria",
  "Sandra de Romero",
  "Santa Ana",
  "Santa Cruz",
  "Santa Ercilia",
  "Santa Fe",
  "Santa Filomena",
  "Santa Librada",
  "Santa Lucia",
  "Santa Rosa",
  "Santiago Liniers",
  "Santiago Zibelman",
  "Santiago del Estero",
  "Santo Domingo",
  "Santo Tomé",
  "Sara Sáenz Cavia de Morales Torre",
  "Sargento Juan Bautista Cabral",
  "Sargento Lemos",
  "Sebastian Gaboto",
  "Sebastián Gaboto",
  "Secundino Antonio Riquelme",
  "Segovia Higinio",
  "Senador Mancini",
  "Senillosa",
  "Sevilla",
  "Sgto. Aníbal Máximo Sotelo",
  "Sgto. Baigorria",
  "Sgto. Lemos",
  "Sicilia",
  "Silverio Ramírez",
  "Silvina Ocampo",
  "Simón Muchnik",
  "Siracusa",
  "Socompa",
  "Sra. Ermida Moreyra de Silva (107)",
  "Stella Gutierrez",
  "Suecia",
  "Suipacha",
  "Suiza",
  "Sánchez de Bustamante",
  "Tacuari",
  "Tacuarí",
  "Tafí del Valle",
  "Tala",
  "Tampico",
  "Taragui",
  "Taragüí",
  "Tartagal",
  "Teniente C. A. Benitez",
  "Teniente Cundom",
  "Teniente Daniel Antonio Jukic",
  "Teniente Jorge Alberto Vazquez",
  "Teniente Juan José Arraras",
  "Teresa de Calcuta",
  "Thomas Edison",
  "Tierra del Fuego",
  "Tilcara",
  "Timbó",
  "Timoteo Grillo",
  "Tobias Garzón",
  "Tolosa",
  "Tomás Godoy Cruz",
  "Tomás Mayol",
  "Tontal",
  "Toribia de los Santos Sosa",
  "Trento",
  "Tres Sargentos",
  "Triunvirato",
  "Tránsito Cocomarola",
  "Trébol de Ases",
  "Tte. Simón Niella",
  "Tucumán",
  "Tulio Francisco Mariño",
  "Tulio Oscar Riera",
  "Tunuyán",
  "Tupac Amaru",
  "Tupungato",
  "Turin",
  "Turín",
  "U.N.N.E.",
  "Unquillo",
  "Uruguay",
  "Ushuaia",
  "Uspallata",
  "Valdepeñas",
  "Valentín Alsina",
  "Valentín Gómez",
  "Valerio Bonastre",
  "Valladolid",
  "Valparaiso",
  "Venecia",
  "Venezuela",
  "Vera Peñaloza",
  "Verdun Roberto",
  "Verona",
  "Verón Juan Alberto",
  "Verón Marciano",
  "Vice Gdor. Clementino Forte",
  "Vice-Gdor. Borges Saa",
  "Vicente López y Planes",
  "Vicente V. Ayala",
  "Victoria Ocampo",
  "Victorino de la Plaza",
  "Viedma",
  "Villavicencio",
  "Viraró",
  "Virgen de Itatí",
  "Virgen de la Candelaria (109)",
  "Virgen de las Mercedes",
  "Vizcaya",
  "Vélez Sarsfield",
  "Yacaré Negro",
  "Yaguarundi",
  "Yapeyú",
  "Yatay",
  "Yerbal",
  "Yofre",
  "Yoguslavia",
  "Yolanda D. Reguera Britez",
  "Yucatán",
  "Yugoslavia",
  "Zacarías Sánchez",
  "Zaragoza",
  "Zitto Segovia",
  "Zuberoa",
  "Álvar Nuñez Cabeza de Vaca",
  "Álvar Núñez Cabeza de Vaca",
  "Ángel Acuña",
  "Ángel Acuña (556)",
  "Ángel Heredia",
  "Ángel Navea",
  "Ángela M. Villan",
  "Ávalos Omar Alberto",
  "Ñaembe",
  "Ñangapirí",
];
